---
- name: Create the systemd_exporter group
  group:
    name: "{{ _systemd_exporter_system_group }}"
    state: present
    system: true
  when: _systemd_exporter_system_group != "root"

- name: Create the systemd_exporter user
  user:
    name: "{{ _systemd_exporter_system_user }}"
    groups: "{{ _systemd_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: _systemd_exporter_system_user != "root"

- block:
    - name: Download systemd_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/povilasv/systemd_exporter/releases/download/v{{ systemd_exporter_version }}/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ systemd_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack systemd_exporter binary
      become: false
      unarchive:
        src: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}/systemd_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate systemd_exporter binaries
      copy:
        src: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}/systemd_exporter"
        dest: "{{ _systemd_exporter_binary_install_dir }}/systemd_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart systemd_exporter
      when: not ansible_check_mode
  when: systemd_exporter_binary_local_dir | length == 0

- name: propagate locally distributed systemd_exporter binary
  copy:
    src: "{{ systemd_exporter_binary_local_dir }}/systemd_exporter"
    dest: "{{ _systemd_exporter_binary_install_dir }}/systemd_exporter"
    mode: 0755
    owner: root
    group: root
  when: systemd_exporter_binary_local_dir | length > 0
  notify: restart systemd_exporter
